language: elixir
env: MIX_ENV=test
notifications:
  recipients:
    - carlos@carloslage.net
elixir:
  - 1.6
script:
  - mix format --check-formatted
  - MIX_ENV=test mix test
after_script:
  - MIX_ENV=dev mix deps.get
  - MIX_ENV=dev mix inch.report
