{deps,
 [ { elixir, ".*",
     {git, "git://github.com/elixir-lang/elixir", {branch, "stable"}}},
   {aleppo, ".*",
    {git, "https://github.com/ChicagoBoss/aleppo.git", {branch, "master"}}},
   {meck, ".*",
    {git, "https://github.com/eproxus/meck.git", {branch, "master"}}},
   { rebar_elixir_plugin, ".*",
          {git, "git://github.com/yrashk/rebar_elixir_plugin", {branch, "master"}}}
 ]
}.
%% get access to mark_keywords in aleppo
{plugins, [rebar_elixir_compiler,rebar_exunit]}.
{lib_dirs, ["deps/elixir/lib"]}.
